### ISSUE TITLE
Unable to load '@webpack-cli/serve' command

### ISSUE THREAD

**Issue by TriDotS** [leanupjs/leanup#3793]
### Environment
```
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (3) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 3.74 GB / 5.81 GB
    Container: Yes
    Shell: 1.32.1 - /bin/ash
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  npmPackages:
    @leanup/cli: 1.2.2 => 1.2.2 
    @leanup/cli-react: 1.2.2 => 1.2.2 
    @leanup/form: 1.2.2 => 1.2.2 
    @leanup/git-hooks: 1.2.2 => 1.2.2 
    @leanup/lib: 1.2.2 => 1.2.2 
    @leanup/openapi-demo: 1.2.2 => 1.2.2 
    @leanup/stack: 1.2.2 => 1.2.2 
    @leanup/stack-react: 1.2.2 => 1.2.2 
    @leanup/stack-webpack: 1.2.2 => 1.2.2 
    @types/react: 17.0.24 => 17.0.24 
    @types/react-dom: 17.0.9 => 17.0.9 
    chromedriver: 93.0.1 => 93.0.1 
    navigo: 8.11.1 => 8.11.1 
    npm-check-updates: 11.8.5 => 11.8.5 
    postcss-windicss: 1.0.0 => 1.0.0 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    rxjs: 7.3.0 => 7.3.0 
    selenium-server: 3.141.59 => 3.141.59 
    typescript: 4.4.3 => 4.4.3 
  npmGlobalPackages:
    corepack: 0.9.0
    npm: 7.24.0
```
```
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (3) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 2.26 GB / 5.81 GB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  npmPackages:
    @leanup/cli: 1.2.2 => 1.2.2 
    @leanup/cli-react: 1.2.2 => 1.2.2 
    @leanup/form: 1.2.2 => 1.2.2 
    @leanup/git-hooks: 1.2.2 => 1.2.2 
    @leanup/lib: 1.2.2 => 1.2.2 
    @leanup/openapi-demo: 1.2.2 => 1.2.2 
    @leanup/stack: 1.2.2 => 1.2.2 
    @leanup/stack-react: 1.2.2 => 1.2.2 
    @leanup/stack-webpack: 1.2.2 => 1.2.2 
    @types/react: 17.0.24 => 17.0.24 
    @types/react-dom: 17.0.9 => 17.0.9 
    chromedriver: 93.0.1 => 93.0.1 
    navigo: 8.11.1 => 8.11.1 
    npm-check-updates: 11.8.5 => 11.8.5 
    postcss-windicss: 1.0.0 => 1.0.0 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    rxjs: 7.3.0 => 7.3.0 
    selenium-server: 3.141.59 => 3.141.59 
    typescript: 4.4.3 => 4.4.3 
  npmGlobalPackages:
    npm: 6.14.15
```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed leanup!**

1.  ```docker run -it node:current-alpine /bin/sh``` oder ```docker run -it node:lts-alpine /bin/sh```
2.  ```mkdir /app```
3.  ```cd /app```
4. ``` npm i -D @leanup/cli @leanup/cli-react```
5. ```npx react create```
6. ```npm run start```

### Expected Behavior

Die Anwendung sollte erfolgreich starten aber es erscheint folgende Fehlermeldung sowohl auf Node LTS & 16
```
/app # npm run start

> /app@1.2.2 start
> npm run serve -- --open


> /app@1.2.2 serve
> cross-env NODE_ENV=development webpack serve --devtool=source-map "--open"

[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (/app/node_modules/webpack-cli/lib/webpack-cli.js:173:21)
    at ServeCommand.apply (/app/node_modules/@webpack-cli/serve/lib/index.js:41:19)
    at loadCommandByName (/app/node_modules/webpack-cli/lib/webpack-cli.js:907:35)
    at async Command.<anonymous> (/app/node_modules/webpack-cli/lib/webpack-cli.js:1483:17)
    at async Promise.all (index 0)
    at async WebpackCLI.run (/app/node_modules/webpack-cli/lib/webpack-cli.js:1521:9)
    at async runCLI (/app/node_modules/webpack-cli/lib/bootstrap.js:11:9)

```
```
/app # npx webpack serve
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (/app/node_modules/webpack-cli/lib/webpack-cli.js:173:21)
    at ServeCommand.apply (/app/node_modules/@webpack-cli/serve/lib/index.js:41:19)
    at loadCommandByName (/app/node_modules/webpack-cli/lib/webpack-cli.js:907:35)
    at async Command.<anonymous> (/app/node_modules/webpack-cli/lib/webpack-cli.js:1483:17)
    at async Promise.all (index 0)
    at async WebpackCLI.run (/app/node_modules/webpack-cli/lib/webpack-cli.js:1521:9)
    at async runCLI (/app/node_modules/webpack-cli/lib/bootstrap.js:11:9)
```

**Comment by TriDotS** [comment]
Workaround: Downgrade ```1.6.0 => 1.5.2``` ```npm i -D @webpack-cli/serve@1.5.2```

**Comment by deleonio** [comment]
Hi @TriDotS , thank you.

I will check your issue next week. Thanks for your help.

**Comment by deleonio** [comment]
I observed the same problem with the following installation:

1. `mkdir app`
2. `cd app`
3. `npm i -D @leanup/cli@2.0.0-rc.2 @leanup/cli-aurelia@2.0.0-rc.2`
4. `npm start`

**Comment by deleonio** [comment]
It is possible that the problem was fixed.

https://github.com/webpack/webpack-cli/issues/2990

**Comment by deleonio** [comment]
See here at the bottom of the page: [Diff 1.2.2 - 1.2.3](https://github.com/leanupjs/leanup/compare/1.2.2...1.2.3)
